version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sharphurt
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: articles-hub-prod
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodbdata:/data/db

  application:
    image: application:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - mongodb

  frontend:
    build: https://github.com/sharphurt/articles-hub-frontend.git
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app